#!/bin/sh /etc/rc.common
 
START=95
USE_PROCD=1

start_service() {
        if test -f "/root/Filament-Sync-Service-for-K1-CFS/service/sync.sh"; then
        SYNCSCRIPT="/root/Filament-Sync-Service-for-K1-CFS/service/sync.sh"
        else
        SYNCSCRIPT="/mnt/UDISK/root/Filament-Sync-Service-for-K1-CFS/service/sync.sh" 
        fi
        procd_open_instance
        procd_set_param command sh ${SYNCSCRIPT}
        procd_set_param respawn  # respawn the service if it exits
        procd_close_instance
}
